[package]
name = "rust-datastructures"
version = "0.1.0"
edition = "2024"
autobenches = false
autoexamples = false
autotests = false


[lib]
test = true

[dependencies]

[dev-dependencies]
k9 = "0.12.0"
